export const materialTypes = [
  {
    ID: 1,
    materials_type: "Leather",
    subcommodity: "Leather \u0026 Leather Goods",
    commodity: "Leather, Rubber \u0026 Wood",
    is_insurance_available: true,
  },
  {
    ID: 2,
    materials_type: "Rubber Products",
    subcommodity: "Rubber",
    commodity: "Leather, Rubber \u0026 Wood",
    is_insurance_available: true,
  },
  {
    ID: 3,
    materials_type: "Wood",
    subcommodity: "Timber \u0026 Wood",
    commodity: "Leather, Rubber \u0026 Wood",
    is_insurance_available: false,
  },
  {
    ID: 4,
    materials_type: "Agricultural products",
    subcommodity: "Processed food/edible items",
    commodity: "Food",
    is_insurance_available: true,
  },
  {
    ID: 5,
    materials_type: "Wheat",
    subcommodity: "Processed food/edible items",
    commodity: "Food",
    is_insurance_available: true,
  },
  {
    ID: 6,
    materials_type: "Vegetables",
    subcommodity: "Processed food/edible items",
    commodity: "Food",
    is_insurance_available: true,
  },
  {
    ID: 7,
    materials_type: "Cotton",
    subcommodity: "All types of fabric and garments",
    commodity: "Fabric \u0026 Textile",
    is_insurance_available: true,
  },
  {
    ID: 8,
    materials_type: "Fabric",
    subcommodity: "All types of fabric and garments",
    commodity: "Fabric \u0026 Textile",
    is_insurance_available: true,
  },
  {
    ID: 9,
    materials_type: "Computer parts",
    subcommodity: "Computer and Telecom Equipment and Peripherals",
    commodity: "Electrical Goods",
    is_insurance_available: true,
  },
  {
    ID: 11,
    materials_type: "Vehicles",
    subcommodity: "Automobiles",
    commodity: "Automobiles/ Machinery/ Metals",
    is_insurance_available: false,
  },
  {
    ID: 12,
    materials_type: "Tyres",
    subcommodity: "Tyres",
    commodity: "Leather, Rubber \u0026 Wood",
    is_insurance_available: true,
  },
  {
    ID: 13,
    materials_type: "Textiles",
    subcommodity: "All types of fabric and garments",
    commodity: "Fabric \u0026 Textile",
    is_insurance_available: true,
  },
  {
    ID: 14,
    materials_type: "Spices",
    subcommodity: "Processed food/edible items",
    commodity: "Food",
    is_insurance_available: true,
  },
  {
    ID: 15,
    materials_type: "Scrap",
    subcommodity: "All Types of Metal Products Excluding Precious Metals",
    commodity: "Automobiles/ Machinery/ Metals",
    is_insurance_available: true,
  },
  {
    ID: 16,
    materials_type: "Rice",
    subcommodity: "Processed food/edible items",
    commodity: "Food",
    is_insurance_available: true,
  },
  {
    ID: 17,
    materials_type: "Refrigerated Goods",
    subcommodity: "Others",
    commodity: "Others",
    is_insurance_available: false,
  },
  {
    ID: 18,
    materials_type: "Books",
    subcommodity: "Stationary Items",
    commodity: "General Merchandise and Plastic Products",
    is_insurance_available: true,
  },
  {
    ID: 19,
    materials_type: "Powder bags",
    subcommodity: "Others",
    commodity: "Others",
    is_insurance_available: false,
  },
  {
    ID: 20,
    materials_type: "Plastic Pipes",
    subcommodity: "Plastic Products",
    commodity: "General Merchandise and Plastic Products",
    is_insurance_available: true,
  },
  {
    ID: 21,
    materials_type: "Packed Food",
    subcommodity: "Processed food/edible items",
    commodity: "Food",
    is_insurance_available: true,
  },
  {
    ID: 22,
    materials_type: "Others",
    subcommodity: "Others",
    commodity: "Others",
    is_insurance_available: false,
  },
  {
    ID: 23,
    materials_type: "Mill Jute Oil",
    subcommodity: "Others",
    commodity: "Others",
    is_insurance_available: false,
  },
  {
    ID: 24,
    materials_type: "Metals",
    subcommodity: "All Types of Metal Products Excluding Precious Metals",
    commodity: "Automobiles/ Machinery/ Metals",
    is_insurance_available: true,
  },
  {
    ID: 25,
    materials_type: "Medicals",
    subcommodity: "Pharma Products",
    commodity: "Pharma \u0026 Chemicals",
    is_insurance_available: true,
  },
  {
    ID: 26,
    materials_type: "Machinery new or old",
    subcommodity: "Machinery, Tools and Spares",
    commodity: "Automobiles/ Machinery/ Metals",
    is_insurance_available: true,
  },
  {
    ID: 27,
    materials_type: "Liquids/Oil",
    subcommodity: "Others",
    commodity: "Others",
    is_insurance_available: false,
  },
  {
    ID: 28,
    materials_type: "Liquids in drums",
    subcommodity: "Others",
    commodity: "Others",
    is_insurance_available: false,
  },
  {
    ID: 29,
    materials_type: "Iron sheets",
    subcommodity: "All Types of Metal Products Excluding Precious Metals",
    commodity: "Automobiles/ Machinery/ Metals",
    is_insurance_available: true,
  },
  {
    ID: 30,
    materials_type: "Industrial Equipments",
    subcommodity: "Machinery, Tools and Spares",
    commodity: "Automobiles/ Machinery/ Metals",
    is_insurance_available: true,
  },
  {
    ID: 31,
    materials_type: "Furniture",
    subcommodity: "Furniture",
    commodity: "Leather, Rubber \u0026 Wood",
    is_insurance_available: true,
  },
  {
    ID: 32,
    materials_type: "Fruits",
    subcommodity: "Processed food/edible items",
    commodity: "Food",
    is_insurance_available: true,
  },
  {
    ID: 33,
    materials_type: "Fertilizers",
    subcommodity: "All types of non hazardous chemicals",
    commodity: "Pharma \u0026 Chemicals",
    is_insurance_available: true,
  },
  {
    ID: 35,
    materials_type: "Cotton seed",
    subcommodity: "Cotton Yarn",
    commodity: "Fabric \u0026 Textile",
    is_insurance_available: false,
  },
  {
    ID: 36,
    materials_type: "Container",
    subcommodity: "Containers",
    commodity: "Others",
    is_insurance_available: false,
  },
  {
    ID: 37,
    materials_type: "Coal",
    subcommodity:
      "Coal (Coke/ Coal/ Peat/ Lignite/Anthracite/ Metallurgical/\nCharcoal)",
    commodity: "Others",
    is_insurance_available: true,
  },
  {
    ID: 38,
    materials_type: "Chemicals",
    subcommodity: "All types of non hazardous chemicals",
    commodity: "Pharma \u0026 Chemicals",
    is_insurance_available: false,
  },
  {
    ID: 39,
    materials_type: "Cement",
    subcommodity: "All types of non hazardous chemicals",
    commodity: "Pharma \u0026 Chemicals",
    is_insurance_available: true,
  },
  {
    ID: 40,
    materials_type: "Building Materials",
    subcommodity: "Others",
    commodity: "Others",
    is_insurance_available: false,
  },
  {
    ID: 41,
    materials_type: "Auto Parts",
    subcommodity: "Auto Spare Parts",
    commodity: "Automobiles/ Machinery/ Metals",
    is_insurance_available: true,
  },
  {
    ID: 42,
    materials_type: "House Hold Goods",
    subcommodity: "Household items - New",
    commodity: "General Merchandise and Plastic Products",
    is_insurance_available: false,
  },
  {
    ID: 43,
    materials_type: "Motor parts",
    subcommodity: "Electrical and Electronic Equipment and Spares",
    commodity: "Electrical Goods",
    is_insurance_available: true,
  },
  {
    ID: 44,
    materials_type: "Steel",
    subcommodity: "All Types of Metal Products Excluding Precious Metals",
    commodity: "Automobiles/ Machinery/ Metals",
    is_insurance_available: true,
  },
  {
    ID: 45,
    materials_type: "Milk",
    subcommodity: "Processed food/edible items",
    commodity: "Food",
    is_insurance_available: true,
  },
  {
    ID: 46,
    materials_type: "Milk Products",
    subcommodity: "Processed food/edible items",
    commodity: "Food",
    is_insurance_available: true,
  },
  {
    ID: 47,
    materials_type: "Coal",
    subcommodity:
      "Coal (Coke/ Coal/ Peat/ Lignite/Anthracite/ Metallurgical/\nCharcoal)",
    commodity: "Others",
    is_insurance_available: true,
  },
  {
    ID: 48,
    materials_type: "Footwear",
    subcommodity: "Footwear",
    commodity: "Others",
    is_insurance_available: true,
  },
  {
    ID: 49,
    materials_type: "Car",
    subcommodity: "Automobiles",
    commodity: "Automobiles/ Machinery/ Metals",
    is_insurance_available: false,
  },
  {
    ID: 50,
    materials_type: "Bike",
    subcommodity: "Automobiles",
    commodity: "Automobiles/ Machinery/ Metals",
    is_insurance_available: false,
  },
  {
    ID: 51,
    materials_type: "Paper rolls",
    subcommodity: "Stationary Items",
    commodity: "General Merchandise and Plastic Products",
    is_insurance_available: true,
  },
  {
    ID: 52,
    materials_type: "Plastic Products",
    subcommodity: "Plastic Products",
    commodity: "General Merchandise and Plastic Products",
    is_insurance_available: true,
  },
  {
    ID: 53,
    materials_type: "Iron bars",
    subcommodity: "All Types of Metal Products Excluding Precious Metals",
    commodity: "Automobiles/ Machinery/ Metals",
    is_insurance_available: true,
  },
  {
    ID: 54,
    materials_type: "Coal Ash",
    subcommodity:
      "Coal (Coke/ Coal/ Peat/ Lignite/Anthracite/ Metallurgical/\nCharcoal)",
    commodity: "Others",
    is_insurance_available: true,
  },
];
